function z = g44(lambda, mu, eta)
% Thomas H. Jordan 2011/03
% Closed form of spherically averaged STG component g44 = G1212
a = eta^2 - 1;
% if a <= 0, error('eta <= 1'), end
z = -(1/(8*mu*(lambda + 2*mu)))*((a + 1)*(lambda + 2*mu)*(tint2(a) - tint4(a))...
    + mu*(tint0(a) - tint2(a)) - mu*(tint2(a) - tint4(a))...
    + a*(lambda + 2*mu)*(tint2(a) - tint4(a))...
    + (lambda + 2*mu)*(tint0(a) - tint2(a)));