function z = g55(lambda, mu, eta)
% Thomas H. Jordan 2011/03
% Closed form of spherically averaged STG component g55 = G1313
a = eta^2 - 1;
% if a <= 0, error('eta <= 1'), end
z = (1/(8*mu*(lambda + 2*mu)))*(2*(a + 1)*(lambda + mu)*(tint2(a) - tint4(a)) - (a + 1)...
    *((a + 1)*(lambda + 2*mu)*tint4(a) + mu*(tint2(a) - tint4(a))...
    + (lambda + 2*mu)*(a*tint4(a) + tint2(a)))...
    - (a + 1)*mu*(tint2(a) - tint4(a)) - (lambda + 2*mu)*(tint0(a) - tint2(a))...
    + (lambda + 2*mu)*(tint2(a) - tint4(a)));